### ISSUE TITLE
Error when running run_language_modeling.py

### ISSUE THREAD

**Issue by zhaijj** [jerryji1993/DNABERT#1]
Hi,

I tried to run DNABERT as shows in README, but I can not run the following command:

```bash
cd examples

export KMER=6
export TRAIN_FILE=sample_data/pre/6_3k.txt
export TEST_FILE=sample_data/pre/6_3k.txt
export SOURCE="/home/malab14/Research/DeepTFBS/DNABERT"
export OUTPUT_PATH="/home/malab14/Research/DeepTFBS/DNABERT/output"

python run_language_modeling.py \
    --output_dir $OUTPUT_PATH \
    --model_type=dna \
    --tokenizer_name=dna$KMER \
    --config_name=$SOURCE/src/transformers/dnabert-config/bert-config-$KMER/config.json \
    --do_train \
    --train_data_file=$TRAIN_FILE \
    --do_eval \
    --eval_data_file=$TEST_FILE \
    --mlm \
    --gradient_accumulation_steps 25 \
    --per_gpu_train_batch_size 10 \
    --per_gpu_eval_batch_size 6 \
    --fp16 \
    --save_steps 500 \
    --save_total_limit 20 \
    --max_steps 200000 \
    --evaluate_during_training \
    --logging_steps 500 \
    --line_by_line \
    --learning_rate 4e-4 \
    --block_size 512 \
    --adam_epsilon 1e-6 \
    --weight_decay 0.01 \
    --beta1 0.9 \
    --beta2 0.98 \
    --mlm_probability 0.025 \
    --warmup_steps 10000 \
    --overwrite_output_dir \
    --n_process 10
```

I got an error like this:

```bash
Traceback (most recent call last):
  File "run_language_modeling.py", line 858, in <module>
    main()
  File "run_language_modeling.py", line 762, in main
    tokenizer = tokenizer_class.from_pretrained(args.tokenizer_name, cache_dir=args.cache_dir)
  File "/home/malab14/Research/DeepTFBS/DNABERT/src/transformers/tokenization_utils.py", line 377, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/malab14/Research/DeepTFBS/DNABERT/src/transformers/tokenization_utils.py", line 469, in _from_pretrained
    raise EnvironmentError(msg)
OSError: Couldn't reach server at '{}' to download vocabulary files.
```

Could you give me a hand?

**Comment by Zhihan1996** [comment]
I am sorry that this is a bug of our original code. I have fixed it. Please reinstall the repo with ```git install --editable .```, and follow the commands in README. It should work fine.

**Comment by zhaijj** [comment]
@Zhihan1996 
Hi, Zhihan
I reinstalled the  repo but another error exists:
```bash
<class 'transformers.tokenization_dna.DNATokenizer'>
Traceback (most recent call last):
  File "run_pretrain.py", line 885, in <module>
    main()
  File "run_pretrain.py", line 789, in main
    tokenizer = tokenizer_class.from_pretrained(args.tokenizer_name, cache_dir=args.cache_dir)
  File "/home/malab14/Research/DeepTFBS/DNABERT/src/transformers/tokenization_utils.py", line 377, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/malab14/Research/DeepTFBS/DNABERT/src/transformers/tokenization_utils.py", line 479, in _from_pretrained
    list(cls.vocab_files_names.values()),
OSError: Model name 'dna6' was not found in tokenizers model name list (dna3, dna4, dna5, dna6). We assumed 'dna6' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.
```

**Comment by Zhihan1996** [comment]
This error happens when it can not access to the following vocab file ```https://raw.githubusercontent.com/jerryji1993/DNABERT/master/src/transformers/dnabert-config/bert-config-6/vocab.txt```. Does your server have network access?

**Comment by jerryji1993** [comment]
Will mark this as closed for now and please feel free to let us know if there is any follow-up questions!
