### ISSUE TITLE
Problem with reading the dev.tsv in find_motif.py

### ISSUE THREAD

**Issue by merouone** [jerryji1993/DNABERT#14]
I tried to run the script to find motifs, but it seems that a problem with reading the file dev.tsv.  Pandas reads the .csv file as a one dimension.  When the script reaches this line 87 `dev.columns = ['sequence','label'] ` it bugs.
Further investigations, pandas except only one column but it finds 2, Like if the `dev = pd.read_csv(os.path.join(args.data_dir,"dev.tsv"),sep='\t',header=None) ` separation is not taken in account resulting one column.

```
Index(['sequence  label'], dtype='object')
Traceback (most recent call last)

 File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "find_motifs.py", line 113, in <module>
    main()
  File "find_motifs.py", line 88, in main
    print(dev[1])
  File "/home/miniconda3/envs/dnabert/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/miniconda3/envs/dnabert/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 1
```

**Comment by mitchgill16** [comment]
Hi I think I had this issue. If I remember correctly my dev.tsv file's first line was 'sequence \t label'. I assume yours would be as well as finetuning in previous steps reads in the dev.tsv with pandas but automatically assigns a header to the first line. My solution was to change line 86
from
pd.read_csv(os.path.join(args.data_dir,"dev.tsv"),sep='\t',header=None)
to
pd.read_csv(os.path.join(args.data_dir,"dev.tsv"),sep='\t')

and comment out line 87
#dev.columns = ['sequence','label']

Hope this helps :)
