### ISSUE TITLE
Hello! I met "StopIteration" Error when trying to run DNABERT using example data 

### ISSUE THREAD

**Issue by hjgwak** [jerryji1993/DNABERT#19]
Hello. I have a huge interest in this DNABERT model.
I ran the exact same command for pre-training using example data.
BUT, I got the following ERROR.

```
Traceback (most recent call last):
  File "run_pretrain.py", line 888, in <module>
    main()
  File "run_pretrain.py", line 838, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "run_pretrain.py", line 434, in train
    outputs = model(inputs, masked_lm_labels=labels) if args.mlm else model(inputs, labels=labels)
  File "/root/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/root/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
StopIteration: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/root/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/DNABERT/src/transformers/modeling_bert.py", line 998, in forward
    encoder_attention_mask=encoder_attention_mask,
  File "/root/miniconda3/envs/dnabert/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/DNABERT/src/transformers/modeling_bert.py", line 745, in forward
    extended_attention_mask = extended_attention_mask.to(dtype=next(self.parameters()).dtype)  # fp16 compatibility
StopIteration
```

The version and build of packages are listed in bellow
```
pytorch      |  1.8.1   |    py3.6_cuda10.2_cudnn7.6.5_0
cudatoolkit  |  10.2.89 |    hfd86e86_0
transformers |  2.5.0   |    dev_0
```

OS: Linux 16.04
Graphic Cards INFO (nvidia-smi)
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-DGXS...  On   | 00000000:07:00.0 Off |                    0 |
| N/A   36C    P0    39W / 300W |     51MiB / 32505MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-DGXS...  On   | 00000000:08:00.0 Off |                    0 |
| N/A   36C    P0    39W / 300W |      1MiB / 32508MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-DGXS...  On   | 00000000:0E:00.0 Off |                    0 |
| N/A   37C    P0    38W / 300W |      1MiB / 32508MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-DGXS...  On   | 00000000:0F:00.0 Off |                    0 |
| N/A   36C    P0    37W / 300W |      1MiB / 32508MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     37975      G   /usr/lib/xorg/Xorg                 49MiB |
|    1   N/A  N/A     37975      G   /usr/lib/xorg/Xorg                  0MiB |
|    2   N/A  N/A     37975      G   /usr/lib/xorg/Xorg                  0MiB |
|    3   N/A  N/A     37975      G   /usr/lib/xorg/Xorg                  0MiB |
+-----------------------------------------------------------------------------+
```

**Comment by Zhihan1996** [comment]
Hi,

Thanks for your interest! 

This is my first time seeing this issue. Have you successfully installed the `apex` package?

**Comment by hjgwak** [comment]
When I asked the question, it was not installed.
But, after install, the same error also occurs.
(I installed apex package using conda
"conda install -c conda-forge nvidia-apex")

On my other GPU server, multi-GPU processing works well.
no apex package is installed on that server.
pytorch version is 1.6.0

Although I have downgrade pytorch version to 1.6.0 on the server that error occurred, the same error still occurs.

**Comment by Zhihan1996** [comment]
Can you try to run the code without the `--fp16` tag. If this works, you may install the `apex` package based on the official instructions (https://github.com/NVIDIA/apex).

**Comment by hjgwak** [comment]
The same error still occurs though run the code without the --fp16 tag.

After upgrade pytorch to 1.8 on the server which has no error for multi-GPU processing,
the same error also occurs.

I guess that the version of pytorch and cudatoolkit may affect parallel processing.
Can you inform the version of packages installed on your workspace?

**Comment by Celestial-Bai** [comment]
I met the same problem with you. Hope it can solved quickly.

**Comment by Zhihan1996** [comment]
Hi,

We used `pytorch=1.4` + `cudatoolkit=10.0` + `python=3.6`. Could you try this setting?

**Comment by hjgwak** [comment]
It works!!!! 🎉
no error occurs on PyTorch 1.4

This problem seems to be caused by a PyTorch update
[https://github.com/huggingface/transformers/issues/8145#issuecomment-721044942](url)
Since, in a few cases, no error occurs on PyTorch >= 1.5, it seems that there is a way to resolve this issue on a higher version of PyTorch.
Unfortunately, I cannot find a way to fix this issue.

A simple way is to downgrade PyTorch to 1.4.

Thanks for your kind response with interest. :)
