### ISSUE TITLE
example for Fine-tune with pre-trained model is not working

### ISSUE THREAD

**Issue by woreom** [jerryji1993/DNABERT#36]
So with this input following the instructions in README file
```
export KMER=6
export MODEL_PATH='/mnt/d/M3/Projects/BCB/DNABERT/models/6mer/'
export DATA_PATH='/mnt/d/M3/Projects/BCB/DNABERT/examples/sample_data/ft/prom-core/6'
export OUTPUT_PATH='/mnt/d/M3/Projects/BCB/DNABERT/examples/OUTPUT/'

python run_finetune.py \
    --model_type dna \
    --tokenizer_name=dna$KMER \
    --model_name_or_path $MODEL_PATH \
    --task_name dnaprom \
    --do_train \
    --do_eval \
    --data_dir $DATA_PATH \
    --max_seq_length 75 \
    --per_gpu_eval_batch_size=16   \
    --per_gpu_train_batch_size=16   \
    --learning_rate 2e-4 \
    --num_train_epochs 3.0 \
    --output_dir $OUTPUT_PATH \
    --evaluate_during_training \
    --logging_steps 100 \
    --save_steps 4000 \
    --warmup_percent 0.1 \
    --hidden_dropout_prob 0.1 \
    --overwrite_output \
    --weight_decay 0.01 \
    --n_process 8
```
I get the error
```
Loading features from cached file /mnt/d/M3/Projects/BCB/DNABERT/examples/sample_data/ft/prom-core/6/cached_train_6mer_75_dnaprom
06/23/2021 06:47:35 - INFO - __main__ -   ***** Running training *****
06/23/2021 06:47:35 - INFO - __main__ -     Num examples = 53277
06/23/2021 06:47:35 - INFO - __main__ -     Num Epochs = 3
06/23/2021 06:47:35 - INFO - __main__ -     Instantaneous batch size per GPU = 16
06/23/2021 06:47:35 - INFO - __main__ -     Total train batch size (w. parallel, distributed & accumulation) = 16
06/23/2021 06:47:35 - INFO - __main__ -     Gradient Accumulation steps = 1
06/23/2021 06:47:35 - INFO - __main__ -     Total optimization steps = 9990
/mnt/d/M3/Projects/BCB/DNABERT/models/6mer/
Traceback (most recent call last):
  File "run_finetune.py", line 1282, in <module>
    main()
  File "run_finetune.py", line 1097, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "run_finetune.py", line 237, in train
    global_step = int(args.model_name_or_path.split("-")[-1].split("/")[0])
ValueError: invalid literal for int() with base 10: ''
(dnabert) woreom@AsusFanap:/mnt/d/M3/Projects/BCB/DNABERT/examples$
```
I also added a `print(args.model_name_or_path)`  to `run_finetune.py` to see what this variable is.
It loads the model fine, I couldn't figure out what this line is doing.
Can you guys help me? Am I doing something wrong or something?

**Comment by mosala777** [comment]
I had a similar issue. Are you sure the paths to your pre-trained model and data are similar to those in the tutorial? The paths should be exactly similar to check for any checkpoints.

**Comment by woreom** [comment]
> I had a similar issue. Are you sure the paths to your pre-trained model and data are similar to those in the tutorial? The paths should be exactly similar to check for any checkpoints.

they were correct paths, the tutorial just said model_path, I gave the "global_step" argument the value 0 manually and it started working
