### ISSUE TITLE
running DNABERT pretrain.py file output environment error

### ISSUE THREAD

**Issue by alexwu66666** [jerryji1993/DNABERT#50]
Hi there,

I am running the DNABERT pretrain.py as instructed by the readme file, once it worked well and started the model training, while when I re-build the environment after a week, the system output the error as below:

08/30/2021 21:23:17 - WARNING - __main__ -   Process rank: -1, device: cpu, n_gpu: 0, distributed training: False, 16-bits training: False
Traceback (most recent call last):
  File "/home/wuchao/dl/DNABERT/src/transformers/configuration_utils.py", line 225, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_pretrain.py", line 885, in <module>
    main()
  File "run_pretrain.py", line 781, in main
    config = config_class.from_pretrained(args.config_name, cache_dir=args.cache_dir)
  File "/home/wuchao/dl/DNABERT/src/transformers/configuration_utils.py", line 176, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/wuchao/dl/DNABERT/src/transformers/configuration_utils.py", line 241, in get_config_dict
    raise EnvironmentError(msg)
OSError: Model name 'PATH_TO_DNABERT_REPO/src/transformers/dnabert-config/bert-config-6/config.json' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/PATH_TO_DNABERT_REPO/src/transformers/dnabert-config/bert-config-6/config.json/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Not only for the terminal training version, but also for the google colab version, may I ask if anyone could help me solve this issue?

Thanks a lot!

Best regards,
Chao

**Comment by caocao0525** [comment]
Your error message is the exact same one I got when I ran the model. Did you get the solution after that?

**Comment by caocao0525** [comment]
I figured it out what was causing the problem. It was just because I didn't change the path 'PATH_TO_DNABERT_REPO' in the line 'export SOURCE=PATH_TO_DNABERT_REPO'! Perhaps I didn't read the lines carefully. So changing the path into the real path solved the problem and it started training. I guess you already figured it out but I am just writing here to help someone who experiences a similar issue.

**Comment by alexwu66666** [comment]
> 

Hi there,

I figured it out on google colab, not our local machine.

Best regards,
Chao

**Comment by sobhanAhmadian** [comment]
I have same problem on google colab, anyone can help?

**Comment by sobhanAhmadian** [comment]
I replaced
`./content/drive/MyDrive/DNABERT/examples/sample_data/ft/6`
with
`/content/drive/MyDrive/DNABERT/examples/sample_data/ft/6`
and it predicts well.
