### ISSUE TITLE
Model name 'dna6' was not found in tokenizers model name list

### ISSUE THREAD

**Issue by BioSenior** [jerryji1993/DNABERT#55]
Hi there,

I am running the DNABERT run_finetune.py as instructed by the readme file. It works well at my workstation, but when I run the same code on the server, it reports the following error:

OSError: Model name 'dna6' was not found in tokenizers model name list (dna3, dna4, dna5, dna6). We assumed 'dna6' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.

I wonder why "Model name 'dna6' was not found in tokenizers model name list (dna3, dna4, dna5, dna6)"? It seems so strange, because dna6 is definitely in the list.

Thanks for the answer!

**Comment by ksenia007** [comment]
I have the exactly the same problem, runs fine on workstation but not on the server and gives the same error!

**Comment by ksenia007** [comment]
I think I've figured out the issue! For me the error was message was generated [here](https://github.com/jerryji1993/DNABERT/blob/2946e8dbe03775f97f3493f752b901466a533ad0/src/transformers/tokenization_utils.py#L458) and was coming from the [loading](https://github.com/jerryji1993/DNABERT/blob/2946e8dbe03775f97f3493f752b901466a533ad0/src/transformers/tokenization_utils.py#L446) of the vocab files. By default, `vocab_files` are in fact links to the files and the server would not allow me to download files from running code. If you download the vocab files separately, and then provide path to the file instead of the 'dna6' it seems to work!

**Comment by BioSenior** [comment]
It works！Thank you very much!

**Comment by ryao-mdanderson** [comment]
Hello @ksenia007 and @BioSenior 👍 

Thank you for sharing.
I have the same error message when I ran 'python run_pretrain.py' followed in README.
OSError: Model name 'dna6' was not found in tokenizers model name list (dna3, dna4, dna5, dna6). 

If I search vocab file in my DNABERT directory, I have the followings:
[ ~DNABERT]$ find . -name vocab*
./examples/ft/6/vocab.txt
./examples/ft/6/pre/vocab.txt
./examples/ft/6/pre_2_old/vocab.txt
./examples/ft/6-bk/vocab.txt
./src/transformers/dnabert-config/bert-config-6/vocab.txt
./src/transformers/dnabert-config/bert-config-4/vocab.txt
./src/transformers/dnabert-config/bert-config-5/vocab.txt
./src/transformers/dnabert-config/bert-config-3/vocab.txt

May you please advise what to change in the commands to go through this error?

**Comment by ksenia007** [comment]
@ryao-mdanderson I am not sure if you have the same problem. However, I believe that if you specify just `dna6` as a  tokenizer name, it tries to load `vocab.txt` from these [links](https://github.com/jerryji1993/DNABERT/blob/2946e8dbe03775f97f3493f752b901466a533ad0/src/transformers/tokenization_dna.py#L35) and not access files from the source folder. For me, I downloaded the `vocab.txt` file into my `data` folder using `wget`, and then in `tokenizer_name` just passed `path/to/directory/vocab.txt`. 

Sorry if that does not help in your case!

**Comment by ryao-mdanderson** [comment]
@ksenia007 👍 

Thank you very much. I got it. since I am running the code in a compute cluster node which does not have internet access, I followed your suggestion, change in tokenizer_name by passing the path/to/directory/vocab.txt. It works now.

**Comment by smruti241** [comment]
@ksenia007, @ryao-mdanderson I am getting the same error and I tried the same solution but didnt work at all.
Traceback (most recent call last):
  File "/home/smrutip/smruti/DNABERT/src/transformers/configuration_utils.py", line 225, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/run_pretrain.py", line 886, in <module>
    main()
  File "examples/run_pretrain.py", line 790, in main
    tokenizer = tokenizer_class.from_pretrained(args.tokenizer_name, cache_dir=args.cache_dir)
  File "/home/smrutip/smruti/DNABERT/src/transformers/tokenization_auto.py", line 181, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/smrutip/smruti/DNABERT/src/transformers/configuration_auto.py", line 183, in from_pretrained
    pretrained_model_name_or_path, pretrained_config_archive_map=ALL_PRETRAINED_CONFIG_ARCHIVE_MAP, **kwargs
  File "/home/smrutip/smruti/DNABERT/src/transformers/configuration_utils.py", line 241, in get_config_dict
    raise EnvironmentError(msg)
OSError: Model name 'dna6' was not found in model name list. We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/dna6/config.json' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

Can you please help me regarding this?

**Comment by 120L021101** [comment]
> I think I've figured out the issue! For me the error was message was generated [here](https://github.com/jerryji1993/DNABERT/blob/2946e8dbe03775f97f3493f752b901466a533ad0/src/transformers/tokenization_utils.py#L458) and was coming from the [loading](https://github.com/jerryji1993/DNABERT/blob/2946e8dbe03775f97f3493f752b901466a533ad0/src/transformers/tokenization_utils.py#L446) of the vocab files. By default, `vocab_files` are in fact links to the files and the server would not allow me to download files from running code. If you download the vocab files separately, and then provide path to the file instead of the `dna6` it seems to work!

you are so nb
